### ISSUE TITLE
关于数据预处理

### ISSUE THREAD

**Issue by liufangcen** [erfect2020/DecompositionForFusion#1]
您好！非常感谢您对图像融合领域做出的巨大贡献！

请问在我们使用红外和可见光数据集时是否需要对图像进行一定的处理，比如将图像放到同一个文件夹下？修改文件名？

作者是否能够提供一个关于测试数据的样例？

期待得到作者的回复！

**Comment by erfect2020** [comment]
谢谢，不需要额外的预处理。红外可见光名字需要对应，红外可见光图像分别放两个文件夹。
具体测试路径参考yaml文件
红外可见光数据集：https://github.com/hanna-xu/RoadScene

**Comment by liufangcen** [comment]
> 

感谢您的回答。

**Comment by erfect2020** [comment]
不客气
