### ISSUE TITLE
关于test的指标SSIM与论文Table 2里不一致的问题

### ISSUE THREAD

**Issue by luoyu5023** [erfect2020/DecompositionForFusion#4]
您好，感谢您做出的非常有意义的工作，您设计图像融合的巧妙思路让我获益匪浅，有一些小问题希望您能帮我解答。
我在复现您的代码时，使用 MFIF Dataset（Zhang)对多聚焦图像进行融合时，使用了您给出的model权重和EMFF_Test_Dataset.yaml，SSIM和PSNR的指标是0.859和28.22，与论文里给出的0.928、28.13在SSIM项有比较大的差异。（为了使灰度图适配于encoder，我采取的处理方法是repeat(1.3,1,1)处理）
此外，我使用RealMFF数据集时，也出现了SSIM与论文给出的数值相差较大的情况，例如我计算出来的SSIM是0.9306，与论文里Real-MFF noref SSIM=0.969也有一定差距，您认为是否是我在计算SSIM出错了？还是说有其他细节我所忽视了。
期待您的回信！

**Comment by erfect2020** [comment]
感谢您关注我们的工作。
多聚焦图像应该输入的是原图，不是灰度图。
ssim 和 psnr 计算时 我使用了Matlab。请对比 Y 通道和原图直接计算的结果。
另外，建议自己在自己的机器上训练模型，以避免软件包版本不同引发的误差。

**Comment by luoyu5023** [comment]
谢谢您的回复，很抱歉我没有及时看到。
我依然有一些困惑，希望您可以解答：

1，对于Real-MFF数据集，确实是输入原图，但测试 MFIFB dataset by Zhang [53]的时候，里面是有灰度图的，请问您是怎么处理的呢？

2，在论文的Table 2里的指标SSIM，您在使用matlab的计算的时候，使用了内置的ssim函数吗（我这么计算的结果误差较大），还是一些通用的公开的代码（我看到在[https://github.com/Linfeng-Tang/Evaluation-for-Image-Fusion](url)这里，计算SSIM还有MEF-SSIM、MS_SSIM等方法）我测试时计算的结果反而比较接近mef_ssim、MS_SSIM

3，您提到的“请对比 Y 通道和原图直接计算的结果”，按照我的理解，本文中DeFusion是直接计算原图不涉及YCbCr，而PMGI、U2Fusion等方法是融合Y通道，按照各自方法的情况进行融合，然后计算指标进行对比是吗

谢谢您的提醒，我会在自己的机器重新训练。

**Comment by erfect2020** [comment]
1. 我没有注意到灰度图的问题，我应该直接当成 RGB 图了。这个应该对最终的数据集评测指标影响不大
2. matlab 里面也有 ms-ssim。mef-ssim 不适用多聚焦任务。
3. 是的。所有对比方法要公平的统一评测，比如统一RGB类型或者统一 Y 通道。总之在你自己的实验设置下，要公平比较。

**Comment by luoyu5023** [comment]
非常感谢您的耐心回复。
所以您的论文计算SSIM是使用了Matlab的内置ms-ssim计算函数 （multissim）是吗
